### ISSUE TITLE
Add a todo list feature on this app 

### ISSUE THREAD

**Issue by sitamadex11** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#12]
Hi I am a GSSoC'21 participant, I want to add a to-do list feature on this app using Room database
may I proceed?
@Rittik-Biswal2000 sir, please assign me this task

**Comment by saipawar108** [comment]
Hi, I am Sayali and I want to work on this todo list feature using javaFx Assign this to me

**Comment by sitamadex11** [comment]
@saipawar108 i have created this issue so please let me do.... Kindly, You create your own issue

**Comment by sitamadex11** [comment]
@Rittik-Biswal2000 sir may I start my work?

**Comment by saipawar108** [comment]
@Rittik-Biswal2000 its okay you take it :)

**Comment by Rittik-Biswal2000** [comment]
Ok , you both can work together on this or you can showcase your individual work . In any case please submit  video demonstrating your feature so that we can assign the task after evaluation

**Comment by saipawar108** [comment]
@Rittik-Biswal2000  Sir , can just tell us what are your requirements for this todo list so that we can proceed accordingly

**Comment by sitamadex11** [comment]
Yes sir then it will be better for us

**Comment by sitamadex11** [comment]
https://user-images.githubusercontent.com/76570320/111021447-523d3780-83f2-11eb-8c5f-8d3da4359c95.mp4

# I have created the basic structure
### I shall:-
* update UI more (will add a check box to finish task)
* make the recycler view swipeable to Delete 
* add a task history page  
* search property
* remainder using notification


**Sir is it ok??**
**Please suggest to me what more I can do if it is ok?**

**Comment by sitamadex11** [comment]
@AltamasBari thankyou sir

**Comment by Rittik-Biswal2000** [comment]
>  GSSoC.College.comrade.1.mp4 
> # I have created the basic structure
> ### I shall:-
> * update UI more (will add a check box to finish task)
> * make the recycler view swipeable to Delete
> * add a task history page
> * search property
> * remainder using notification
> 
> @Rittik-Biswal2000
> **Sir is it ok??**
> **Please suggest to me what more I can do if it is ok?**

yeah , it's great go ahead

**Comment by sitamadex11** [comment]
Okk thank you sir @Rittik-Biswal2000

**Comment by sitamadex11** [comment]
https://user-images.githubusercontent.com/76570320/112861958-ea197180-90d2-11eb-9a5a-c9be0c2f1ede.mp4

Till now I have done this

**Comment by Rittik-Biswal2000** [comment]
@sitamadex11 send the pr. It's awesome

**Comment by sitamadex11** [comment]
Ok, sir sure.
