### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by Rittik-Biswal2000** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#16]
The registration page should have the following components

1.Name
2.DOB
3.Email ID/password
4.Phone Number
5.Registration Number
6.Branch , Year , etc 
7. College Name (Preferably from a dropdown list)

**Comment by Rittik-Biswal2000** [comment]
In the database store these details in the following tree structure

**college_name**
       **Year**
            **Branch**
                  Student details

**Comment by shreyadubey0902** [comment]
I would like to work on it 
Can you please assign the work to me?

**Comment by rasikabakre** [comment]
I really would like to work on the this issue. Would you kindly assign it to me?

**Comment by tanishq-123** [comment]
I would like to help in implementing this, not done yet.

**Comment by vaibhav-c** [comment]
There must be an option to upload a profile photo in the registration page which gets stored in Cloud Storage of Firebase. I would like to work on the same.

**Comment by Gautam204** [comment]
In case the the issue is still open for others I would like to contribute in this project.  I am a participant in GSSOC'21. Please assign this issue to me.

**Comment by etamys** [comment]
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()

if it's open please check this.

**Comment by etamys** [comment]
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()
check this

**Comment by etamys** [comment]
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()
check this

**Comment by etamys** [comment]
![Screenshot_2021-03-18-14-08-52-114_com example tt](https://user-images.githubusercontent.com/57357736/111635724-ce35e600-881d-11eb-915a-d80cca613f24.jpg)
check this

**Comment by AltamasBari** [comment]
@etamys Send the PR asap.

**Comment by etamys** [comment]
my code is ready i will upload it today after some changes, project-4admin I have a request, please be online. because bhaut logo ne issue create kiye h..I have also created some but you didn't answer. to mene aage work nhi kiya...

**Comment by etamys** [comment]
hi
I tried to PR but it's shows me permission denied to etamys

**Comment by etamys** [comment]
Hi
I did 
regex,
password hidden
scrollable


forgot btn is not good in Registration UI for this  ,I can this Desgin login UI  . I will make new PR for Login UI here forgot btn will look good
