### ISSUE TITLE
Logout feature. 

### ISSUE THREAD

**Issue by tanishq-123** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#25]

**Comment by TanuSharma19** [comment]
Sir ,i want to work on this issue if you will assign me this task. I will add the logout option so that ww can return to the registration login page

**Comment by tanishq-123** [comment]
I am a participant as well and have opened this issue. Waiting to be approved by admin.

**Comment by AltamasBari** [comment]
@tanishq-123 Is assigned as per the first come first serve basis. If he /she is unable to do, then others will be considered.

**Comment by TanuSharma19** [comment]
Ohk

**Comment by tanishq-123** [comment]
Hey Altamas, sent PR for the logout feature, kindly have a look.

**Comment by Sawmya1** [comment]
I want to work on this issue. Please assign me this.

**Comment by tanishq-123** [comment]
https://user-images.githubusercontent.com/55457071/111792657-7618e580-88ea-11eb-926a-bee7e5fb613f.mp4

**Comment by AmanBisht01** [comment]
@AltamasBari @tanishq-123 
Can I work on this issue as Tanishq-123 is unable to resolve merge conflicts in 14 days.?

**Comment by Khushi-24** [comment]
@Rittik-Biswal2000 Can I work on this issue if no one else is working?
