### ISSUE TITLE
Changing Default Buttons and Edit Texts. Adding cards to faculty list.

### ISSUE THREAD

**Issue by vaibhav-c** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#36]

**Comment by vaibhav-c** [comment]
I would like to work on this issue. I am GSSOC 21 participant.

**Comment by RiyaKumar00** [comment]
Hey @vaibhav-c ! I have already raised an issue regarding the UI/UX of the faculty list page. I am a GSSOC'21 participant as well and was looking forward to working on the issue.

**Comment by vaibhav-c** [comment]
Ok, then I will leave the faculty page. I will change things elsewhere.
