### ISSUE TITLE
typo in README.md file

### ISSUE THREAD

**Issue by RashikaJoshi-777** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#37]

**Comment by RashikaJoshi-777** [comment]
i want to work for this

**Comment by Sawmya1** [comment]
I want to work on this issue. Please assign me this. I'm a GSSoC contributor.

**Comment by Nitish1702** [comment]
Hi, I want to work on this. Please assign me this issue.

**Comment by AltamasBari** [comment]
Please provide a description while creating an issue.

**Comment by RashikaJoshi-777** [comment]
> Please provide a description while creating an issue.

there are typo in README file which i want to fix , so please assign this issue to me [GSSOC 21]
