### ISSUE TITLE
Error on Login Page and SignUp Page

### ISSUE THREAD

**Issue by aditya-190** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#47]
On Hitting Sign In or Sign Up Button Without entering any details make the app to crash.
I could resolve this issue.

@GSSOC'21 Participant

**Comment by etamys** [comment]
hi 
I can Solve this issue by use some exception on it or some validation on field.

**Comment by rahulsain** [comment]
can i work on this issue?

**Comment by etamys** [comment]
it's already solved...

**Comment by aditya-190** [comment]
Successful
