### ISSUE TITLE
Login UI + Authentication (etamys)

### ISSUE THREAD

**Issue by etamys** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#65]
assign this to me it's ready you can check
![WhatsApp Image 2021-03-30 at 9 25 08 AM](https://user-images.githubusercontent.com/57357736/112931730-4d8aba00-913a-11eb-95cb-8045c9cf2d4d.jpeg)

**Comment by Rittik-Biswal2000** [comment]
Please send a pr along with implementation video.

**Comment by etamys** [comment]
Actually i did it in my latest PR . which you merged currently.🥰
