### ISSUE TITLE
UI of home page it's not look good

### ISSUE THREAD

**Issue by etamys** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#69]
![c0e21c9eaf949d61f0ce769b3334a4f3](https://user-images.githubusercontent.com/57357736/112941286-f261c300-914b-11eb-814e-f3d954fa3595.png)

this is design. we can it's open for everyone...anyone if want this issue take it

**Comment by etamys** [comment]
![IMG_20210330_142744](https://user-images.githubusercontent.com/57357736/112962632-35c82b80-9164-11eb-86e3-35ffb991ad88.jpg)

**Comment by Rittik-Biswal2000** [comment]
@etamys please go ahead . Please make sure the subject names are dynamic and if possible try to make the icons neutral , i.e. not related to any particular subjects

**Comment by etamys** [comment]
ok.. I'm was only waiting for your permission.
 Thank YOu

**Comment by etamys** [comment]
for upper part is this OK
![112941286-f261c300-914b-11eb-814e-f3d954fa3595](https://user-images.githubusercontent.com/57357736/113318928-94410580-932e-11eb-9cee-c973fdcd94f9.png)


and for lower part.. 
![112962632-35c82b80-9164-11eb-86e3-35ffb991ad88](https://user-images.githubusercontent.com/57357736/113319133-c3577700-932e-11eb-9f36-1b14edf90c30.jpg)


 i will use this design for home layout . when we open screen. the first screen is shown for user would be this and in this part of UI i will use notes section of current of UI and replace all the subject from notes Item like-> DSA, OS

**Comment by sitamadex11** [comment]
may I work on this issue?

**Comment by etamys** [comment]
I already Started @sitamadex11

**Comment by sitamadex11** [comment]
ok no problem @etamys

**Comment by etamys** [comment]
☺

**Comment by etamys** [comment]
<img src="https://user-images.githubusercontent.com/57357736/113336373-f0faeb00-9343-11eb-95e0-a7ea6986bfa8.png" >

current dessign

**Comment by etamys** [comment]
can i finish it here and let them Someone to create issue  or keep going 
1.fetching data from database and show user name and pic
2. current date and time

**Comment by kanikaaggar16** [comment]
Hey I already worked on the main activity and lecture notes activity and it got merged also

**Comment by etamys** [comment]
ya but your design not looks good, i didn't not say you waste you effort, you did very well work, but it's need improvement in UI . we meed strong UI for attract our audience. not just simple one.

**Comment by kanikaaggar16** [comment]
yeah but this is for university students it should not be having many picture or icons. It should have have formal icons to represent. Second the issue assigning was done on first cum first basis.

**Comment by etamys** [comment]
yep ,but I'm not taking your issue, i just modified it. by modifying it
your point would not be deducted.

**Comment by kanikaaggar16** [comment]
so it seems like you are really interested in this project. Why dont we work together if you like ?.

**Comment by etamys** [comment]
ok Sure...

**Comment by etamys** [comment]
My Design is  Ready ,Now I'm Waiting for Bottom Navigation then I will add my Design to the Bottom Navigation

**Comment by etamys** [comment]
yep it's done look at this
![Screenshot (324)](https://user-images.githubusercontent.com/57357736/113516750-a5417f00-9599-11eb-98b3-c717e73ed71d.png)

**Comment by kanikaaggar16** [comment]
What options are you giving in bottom navigation bar?

**Comment by etamys** [comment]
all, but i have not icons to show them

**Comment by etamys** [comment]
notes, Holiday, syllabus, timetable, faculty
