### ISSUE TITLE
Bottom Navigation

### ISSUE THREAD

**Issue by etamys** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#71]
### **Feature request**:
We can add Bottom navigation in app

### **Is your feature request related to a problem? Please describe. (optional)**:
A clear and concise description of what the problem is. 

### **Describe the solution you'd like**:
Bottom Nviagtion like Youtube ,Instagram so user can Switch to Different Fragment easily

### **Describe how this feature will be useful to our readers**:
it's give him a better UI exeperience and it also improve the app Desgin. In Research found that , A better UI of app makes app popular. User Does not need to back to Home screen for every Task.
Example:- When user go for Notes activtiy and at that time he wanted to see holidays Activity. User move back to home screen and then click on Holiday Activtiy. it's so irritating. if we use BottomNavigation he don't need to back . He/She can easily switchh around Activity.

### **Additional context:**
https://lh3.googleusercontent.com/14jax4TqtGJ1R7uteNETMHtrB4_83FOVLCsLW3VxWh17Mle2RiCPiUwPgN0hEXqkCr-281geh88fDMuEZyGVTyhZ_j8hO9RHElEa=w1064-v0
You can check this

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by tanishq-123** [comment]
I will be very much happy to work on this issue.

**Comment by etamys** [comment]
ya Sure , but agr Ye active @AltamasBari  @Rittik-Biswal2000  hee nhi honge to , 
we can't proceed .

**Comment by Rittik-Biswal2000** [comment]
Atlease wait for 48-72 hrs before commenting

**Comment by Rittik-Biswal2000** [comment]
Understand that we are allowing ample time so that project can be completed in a proper manner and contributors can properly check their implementation for any bugs that might have occured

**Comment by Rittik-Biswal2000** [comment]
@tanishq-123 @etamys are you both willing to work on this issue ?

**Comment by tanishq-123** [comment]
Yes I'm

**Comment by etamys** [comment]
yes

**Comment by etamys** [comment]
ya but, In other project , his mentors are so active.
Actually , due to exams I was not able to contribute in Starting , but now I'm free . i want to contribute more and more as i can.
For this  our mentors should need to be active.
48-72 i'ts so long time. 
I don't think that , rather than level 3 issue any issue would take that much of time

**Comment by tanishq-123** [comment]
@AltamasBari I think i won't be able to do it, you can assign it to @etamys

**Comment by etamys** [comment]
hey @tanishq-123  don't be back . it's my first time also . you can take this issue.  if you need full information about this how we implement it i will tell you according to my prospective which i Though.

**Comment by tanishq-123** [comment]
okay, let's do it together. don't know how points will be distributed though.

**Comment by etamys** [comment]
wait i will tell you ,your score.

**Comment by etamys** [comment]
![Screenshot_2021-04-01-23-59-50-329_com android chrome](https://user-images.githubusercontent.com/57357736/113338377-a6c73900-9346-11eb-9085-ab859a46bc8a.jpg)

it's 15

**Comment by tanishq-123** [comment]
No what I'm saying is if we will work together on the same issue then will we both get full points or it will be divided?

**Comment by etamys** [comment]
no, it's not divided 😅.

**Comment by etamys** [comment]
jo PR send krega usi ko milenge

**Comment by tanishq-123** [comment]
okay

**Comment by etamys** [comment]
you can start. working on it. you have to just make 5 bottom nav items and we also need to create 5 fragment and copy a the activities code into fragment.
it's like changing whole Codebase.
big stuff😅😊
i will handle , we can divide task and create two PR s for it. because it big work..👨‍💻🔥😊

**Comment by tanishq-123** [comment]
Let's meet on discord tomorrow. My username is Tanishq(P)

**Comment by etamys** [comment]
![Screenshot (324)](https://user-images.githubusercontent.com/57357736/113516774-cb671f00-9599-11eb-828d-b3c62b5afa55.png)


Bottom Navigation and UI part is Ready

**Comment by etamys** [comment]
But i need icons of faculty,notes,holidays,timetable etc

**Comment by tanishq-123** [comment]
You can take them from drawables.

**Comment by etamys** [comment]
it's  jpg form

**Comment by tanishq-123** [comment]
Check discord

**Comment by apoorva0107** [comment]
Hi, I am willing to work on this under GSSOC'21 with a partner. Please assign

**Comment by etamys** [comment]
@apoorva0107 I already did it but, mentors of this project are not active..so I'm not able to send PR @Rittik-Biswal2000
