### ISSUE TITLE
PDF Reader Functionality

### ISSUE THREAD

**Issue by sitamadex11** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#74]
### **Feature request**:
User can read pdf file from his local storage 

### **Describe how this feature will be useful to our readers**:
In this app all pdfs are static. Therefore It will help users to read the pdfs which they want. 

## sir, I want to work on this issue.
@Rittik-Biswal2000 @AltamasBari

**Comment by Rittik-Biswal2000** [comment]
@sitamadex11 any updates ?

**Comment by sitamadex11** [comment]
sir, the basic structure of the app is ready.

**Comment by sitamadex11** [comment]
https://user-images.githubusercontent.com/76570320/114902257-439fd100-9e33-11eb-85bf-57f038d7055f.mp4

**Comment by sitamadex11** [comment]
https://user-images.githubusercontent.com/76570320/115132128-f3836300-a01a-11eb-9593-0e7c4fb5340f.mp4

sir, there is the basic functionality

**Comment by Rittik-Biswal2000** [comment]
@sitamadex11 Also add a functionality to upload a pdf from the app , store it in local storage and then displaying it in the app

**Comment by sitamadex11** [comment]
for uploading a pdf I need to use firebase storage. Then please add me to the app's firebase as a collaborator

**Comment by sitamadex11** [comment]
Actually, here I have fetched all saved pdf from local storage and displayed them in the app. Now I am working on  the search functionality to find a particular PDF of my storage by using searchable
