### ISSUE TITLE
Required changes in activity_main.xml

### ISSUE THREAD

**Issue by Khushi-24** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#79]
### **Describe the bug:**
activity_main.xml consists of lots of duplicate id's 
Even the layout orientation is also not correct (LinearLayout tag is not ended)

### **To Reproduce:**
1. Rename the id's as per the requirement
2. Change the layout

### **Expected behavior:**
neat assignment of id's
proper orientation

### **Screenshots:**
<img src= "https://user-images.githubusercontent.com/70067211/114384968-05917b80-9bad-11eb-8821-2a57a317a710.png" width=500 height=300>

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Khushi-24** [comment]
Can I make the required changes?

**Comment by Rittik-Biswal2000** [comment]
Yeah @Khushi-24 go ahead

**Comment by AltamasBari** [comment]
Good work @Khushi-24!
