### ISSUE TITLE
add firebase 

### ISSUE THREAD

**Issue by etamys** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#8]
we need to add firebase for storing data like user notes ,syllabus, holiday

**Comment by y-ahuja** [comment]
Hey, I am GSSOC'21 participant and I want work on this feature.
Can you assign this issue to me..

**Comment by etamys** [comment]
i created this issue so please let me work on this. 
@y-ahuja  create your own issue please..

**Comment by y-ahuja** [comment]
Okay

**Comment by Rittik-Biswal2000** [comment]
@etamys please make a demo app demonstrating this feature. Also the documents should be fetched if the device isn't connected to internet
