### ISSUE TITLE
Improve UI of activity_profile.xml with TodoList functionality

### ISSUE THREAD

**Issue by sitamadex11** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#80]
I want to improve the UI of activity_profile.xml and add the TodoList feature.

**Comment by Rittik-Biswal2000** [comment]
@sitamadex11 go ahead , send a pr

**Comment by sitamadex11** [comment]
Okkk thankyou @Rittik-Biswal2000 sir

**Comment by sitamadex11** [comment]
## After the last PR of issue #68 merging by @i-tick sir, due to some misunderstanding the UI of the profile page was downgraded to this :
![demo-problem](https://user-images.githubusercontent.com/76570320/114652758-24565600-9d04-11eb-8006-1cb8a38a1274.png)

### now I want to fix : 
- [ ] the Ui of the page
- [ ] Add the todo functionality
- [ ] logout functionality

#### @Rittik-Biswal2000, @AltamasBari  sir please give a level.
